package com.neuralarc.model;

public enum StrategyEventType {
    STRATEGY_CREATED,
    VALIDATION_FAILED,
    ORDER_SUBMITTED,
    ORDER_STATUS_UPDATED,
    POLL_SUCCESS,
    POLL_ERROR,
    PROFIT_HOLD_ARMED,
    PROFIT_HOLD_UPDATED,
    STRATEGY_COMPLETED,
    STRATEGY_PAUSED,
    STRATEGY_RESUMED,
    STRATEGY_FAILED
}

