package com.neuralarc.model;

public enum StrategyLifecycleState {
    CREATED,
    VALIDATED,
    BASE_BUY_PLACED,
    BASE_BUY_PARTIALLY_FILLED,
    BASE_BUY_FILLED,
    BUY_LIMIT_1_PLACED,
    BUY_LIMIT_1_PARTIALLY_FILLED,
    BUY_LIMIT_1_FILLED,
    BUY_LIMIT_2_PLACED,
    BUY_LIMIT_2_PARTIALLY_FILLED,
    BUY_LIMIT_2_FILLED,
    STOP_LOSS_ACTIVE,
    PROFIT_HOLD_ACTIVE,
    SELL_PLACED,
    SELL_PARTIALLY_FILLED,
    COMPLETED,
    PAUSED,
    FAILED,
    STOPPED
}
