package com.neuralarc.model;

public enum StrategyEventType {
    STRATEGY_CREATED,
    STRATEGY_UPDATED,
    VALIDATION_FAILED,
    ORDER_SUBMITTED,
    ORDER_STATUS_UPDATED,
    POLL_SUCCESS,
    POLL_ERROR,
    STOP_LOSS_ACTIVATED,
    STOP_LOSS_TRIGGERED,
    OPTIONAL_LOSS_EXIT_TRIGGERED,
    TARGET_TRIGGERED,
    PROFIT_HOLD_ARMED,
    PROFIT_HOLD_UPDATED,
    STRATEGY_COMPLETED,
    STRATEGY_PAUSED,
    STRATEGY_RESUMED,
    STRATEGY_STOPPED,
    STRATEGY_FAILED
}
