app.name=NeuralArc
app.version=${version}
app.copyright=Copyright © 2026 NeuralArc. All rights reserved.
app.patent=Patent Pending.
app.splash.duration.millis=2000
app.analytics.enabled=false
app.analytics.endpoint.default=http://localhost:8080/events
alpaca.baseUrl=https://paper-api.alpaca.markets
alpaca.dataUrl=https://data.alpaca.markets
alpaca.mode=PAPER
trading.live.enabled=false
