app.name=NeuralArc
app.version=${version}
app.copyright=Copyright © 2026 NeuralArc. All rights reserved.
app.patent=Patent Pending.
app.splash.duration.millis=2000
app.analytics.endpoint.default=http://localhost:8080/events
