lpaperTrading=true
symbol=NIO
baseBuyPrice=6.21
baseBuyQty=10
stopLossEnabled=true
stopLoss=5.95
sellTriggerPrice=7.00
lossBuyLevel1Price=5.55
lossBuyLevel1Qty=5
lossBuyLevel2Price=4.45
lossBuyLevel2Qty=5
pollingSeconds=2
holdAtTenPercentProfit=false
repeatCycleAfterProfitExitEnabled=false
telemetryEnabled=false

